---

- name: Upgrade all packages
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install Mate DE and some extras
  pacman:
    name: "{{ packages }}"
    state: present

- name: Install vbox utils with X11 support
  shell: yes | pacman -S virtualbox-guest-utils
