---

- name: Disable iptables by default
  service:
    name: iptables
    state: stopped
    enabled: false

- name: Start and enable display manager
  service:
    name: lxdm
    state: started
    enabled: true

- name: Ensure ssh server is running.
  service:
    name: sshd
    state: started
    enabled: true
