---

- name: Ensure wheel group exists
  group:
    name: wheel
    state: present

- name: Ensure wheel group can sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
  validate: 'visudo -cf %s'

- name: Setup user account {{ username }}
  user:
    name: "{{ username }}"
    state: present
    create_home: yes
    groups: wheel
    shell: "/usr/bin/{{ shell }}"
    password: "{{ password }}"

- name: Ensure .config exists in {{ username }}'s homedir
  file:
    path: /home/{{ username }}/.config
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Template monitor config for {{ username }}
  template:
    src: dotfiles/config/monitors.xml.j2
    dest: /home/{{ username }}/.config/monitors.xml
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Template conky config for {{ username }}
  template:
    src: dotfiles/conky.conf.j2
    dest: /home/{{ username }}/.conky.conf
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Ensure autostart directory exists.
  file:
    path: /home/{{ username }}/.config/autostart
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Template conky.desktop for {{ username }}
  template:
    src: dotfiles/config/autostart/conky.desktop.j2
    dest: /home/{{ username }}/.config/autostart/conky.desktop
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
